apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    app: project-aaeo
spec:
  type: ClusterIP
  selector:
    app: project-aaeo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
